type = "javascript"
name = "worker-template-jest-test"
account_id = "your_account_id"
zone_id = "your_zone_id"
compatibility_date = "2021-10-05"
route = "example.com/*"

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"
